name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: cirrusci/flutter:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get packages
      run: sudo flutter pub get
    - name: Run flutter tests
      run: flutter analyze
